FROM alpine:latest

ENV TF_VERSION 1.4.5

RUN apk add git

RUN apk add curl && \
    curl -L https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip && \
    unzip terraform.zip && \
    chmod +x terraform && \
    mv terraform /usr/bin/terraform && \
    rm -f terraform.zip

ADD src/worker/build.sh /
RUN chmod +x /build.sh

ENTRYPOINT [ "/build.sh" ]

