apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plateforms.kappform.dev
spec:
  scope: Namespaced
  group: kappform.dev
  names:
    kind: Plateform
    plural: plateforms
    singular: plateform
    shortNames:
      - infra
      - plateform
      - plateforms
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                latestVersion:
                  type: string
                  pattern: "^[0-9a-zA-Z]*$"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                create_plateform_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    prj-status:
                      type: string
                      default: creating
                      enum:
                      - creating
                      - ready
                      - deleting
            name:
              type: string
              pattern: "^[a-z-A-Z]+"
      additionalPrinterColumns:
#        - name: partenaire
#          type: string
#          jsonPath: .spec.partenaire
        - name: status
          type: string
          jsonPath: .status.create_plateform_fn.prj-status