

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappform-operator
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kappform-operator
  template:
    metadata:
      labels:
        application: kappform-operator
    spec:
      serviceAccountName: kappform-account
      containers:
      - name: kappform-container
        image: ${IMAGE_OPERATOR}
        imagePullPolicy: IfNotPresent
        env:
        - name: GOOGLE_PROJECT
          value: ${GOOGLE_PROJECT}
        - name: IMAGE_WORKER
          value: ${IMAGE_WORKER}
        - name: TFSTATE_BUCKET
          value: ${TFSTATE_BUCKET}
        - name: KUBE_PROVIDER
          value: ${KUBE_PROVIDER}
        - name: TFSTATE_REGION
          value: ${TFSTATE_REGION}