---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kappform-account
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-svc-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-operator
rules:
- apiGroups: ["kappform.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions",]
  verbs: ["*"]  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods", "services"]
  verbs: ["*"]  
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]  
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kappform-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: kappform-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: model-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: worker-svc-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: worker-role
  apiGroup: rbac.authorization.k8s.io